services:
  - type: web
    name: telugu-pdf-server
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
    startCommand: gunicorn app:app
